OrdererOrgs:

  - Name: Orderer
    Domain: network.com
    Specs:
      - Hostname: orderer
        SANS:
          - "127.0.0.1"
PeerOrgs:

  - Name: Org1
    Domain: org1.network.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "127.0.0.1"
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.network.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "127.0.0.1"
    Users:
      Count: 1